name: Bug 反馈
description: 提交你的 Bug 反馈给我们以便我们改进系统
title: "[Bug]: "
labels: [bug]
assignees:
  - deatil
body:
  - type: input
    id: sysver
    attributes:
      label: 系统版本
      description: 请输入您当前使用的项目版本?
      placeholder: 1.0.1
    validations:
      required: true
  - type: input
    id: php
    attributes:
      label: php 版本
      description: 请输入您当前使用的 php 版本?
      placeholder: php 8.0.2
    validations:
      required: true
  - type: input
    id: webman
    attributes:
      label: Webman 版本
      description: 请输入您当前使用的 Webman 版本?
      placeholder: Webman1.4.3
    validations:
      required: true
  - type: dropdown
    id: reappearance
    attributes:
      label: 是否依旧存在
      description: 是否可以在 main 分支复现此 bug?
      options:
        - 可以
        - 不可以
        - 未测试
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: bug描述
      description: 请简要描述 bug 以及复现过程
      placeholder: |
        1. 首先...
        2. 然后...
    validations:
      required: true
  - type: textarea
    id: advise
    attributes:
      label: 修改建议
      description: 您有好的建议或者修改方案可以提供给我们。
